name: delivery
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.18+76

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  get_storage: ^2.0.2
  device_info: ^2.0.2
  package_info: ^2.0.0
  system_info: ^1.0.0
  brasil_fields: ^1.1.1
  geolocator: ^8.0.1
  firebase_core: ^1.0.4
  firebase_analytics: 9.1.9
  file_picker: ^4.2.7
  flutter_spinkit: ^5.0.0
  flutter_pusher: ^1.0.3
  map_launcher: ^2.0.0
  url_launcher: ^6.0.3
  assets_audio_player:
    git:
      url: https://github.com/speedappbr/Flutter-AssetsAudioPlayer.git
      ref: master
  background_locator: 1.6.12
  path_provider: ^2.0.8
  modal_bottom_sheet: ^2.0.1
  image_picker: ^0.8.4+10
  battery_plus: ^2.1.3
  android_device_info: ^1.0.0
  dotted_decoration: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/anim/
    - assets/img/
    - assets/audio/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/static/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway/static/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway/static/Raleway-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Raleway/static/Raleway-Bold.ttf
          weight: 600
        - asset: assets/fonts/Raleway/static/Raleway-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Raleway/static/Raleway-Black.ttf
          weight: 800

    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-Light.ttf
          weight: 300
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-Bold.ttf
          weight: 600
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-Black.ttf
          weight: 800
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
